### ISSUE TITLE
Nanite Ore Detector causes massive slowdown

### ISSUE THREAD

**Issue by nukeguard** [nukeguard/NaniteConstructionSystem#70] opened 2018-11-06 20:51 UTC
When I power on the ore detector with default settings it's fine, but if I change radius to max with the distance upgrades I get freezing and unresponsive desktop and goes away if I turn radius down, or turn off the block.

**Comment by Fank** [comment] 2018-11-06 23:06
i hate the voxel scanning mechanic *tableflip*, was it SP or MP ?

**Comment by nukeguard** [comment] 2018-11-07 02:17
yes in SP, I have not tried this in MP

**Comment by SplenectomY** [comment] 2018-11-12 17:32
Could not reproduce in SP. Went to the middle of an asteroid, set up a facility with an ore detector, loaded on all the range upgrades, maxed the range out and made it scan and i saw no hit to my performance at all.

**Comment by SplenectomY** [comment] 2018-11-12 17:32
Can you zip and send me your save @nukeguard

**Comment by SplenectomY** [comment] 2018-11-16 01:30
Been using this like crazy and can't reproduce in SP or MP. Still has some lock/unlocking issues on parallel threads, but I'm working on that. Doesn't sound at all like what you described

**Comment by nukeguard** [comment] 2018-11-20 05:03
I'll check this out again in the world I have; record it and send world.

**Comment by nukeguard** [comment] 2018-11-20 05:04
may just be my laptop :-D

**Comment by Fank** [comment] 2018-11-20 16:29
Yea there is a thread sleep because of this issue, i needed to throttle the checks, otherwise all cpu cores will hit 100% until finished voxel scanning.

**Comment by SplenectomY** [comment] 2019-01-01 15:57
Fixed as of the latest commit.

**Closed by SplenectomY** 2019-01-01 15:57 UTC
Labels: comp:mining, help wanted, type:bug
