### ISSUE TITLE
When built with a projector - built by is not set

### ISSUE THREAD

**Issue by zMOFOz** [nukeguard/NaniteConstructionSystem#32] opened 2018-08-06 19:16 UTC
When built with a projector - builtby is not set 

I have taken 2 blocks and did a compare for you
https://drive.google.com/open?id=1X8eMlwYDNloyPCx2kY_3MqVi4tfOR6a4

Steps: Porject a ship and build it
now go up to the ship and notice that built by: is missing on the blocks

this bug will cause any player in a faction to start attacking each ship as its built by (nobody)

**Comment by Fank** [comment] 2018-08-06 19:49
Duplicate of #23

**Closed by Fank** 2018-08-06 19:49 UTC
Labels: block:controlfacility, comp:projection, type:duplicate

**Comment by Fank** [comment] 2018-08-06 19:50
Workaround for that is disabling "Target neutral" and change ownership after build to "Me"

**Comment by zMOFOz** [comment] 2018-08-06 19:57
Target Neutral and changing ownership is not possible on a DC server. tell the players that they can bypass the per player PCU limit?

**Comment by zMOFOz** [comment] 2018-08-06 20:01
your thinking owner ship - Built By is the problem

**Comment by Fank** [comment] 2018-08-06 20:01
I know that it is not good for a PvP driven server, but for now its not easy to fix ...
Thats the reason why its planed for 2.0

**Comment by zMOFOz** [comment] 2018-08-06 20:05
I think you talking about something diff of what I am thinking about
Target neutral has no effect
its the built by 
we want the credit of the build to the player so it will go with the PCU per player limit
I think for now we are going to remove the mod until your new update.

I really enjoy this mod but our server is going down because the the players bypassing the PCU limit

**Comment by Fank** [comment] 2018-08-06 20:13
I understand your problem, what i could try is to change https://github.com/nukeguard/NaniteConstructionSystem/blob/master/Data/Scripts/NaniteConstructionSystem/Entities/Targets/NaniteProjectionTargets.cs#L468 to the owner of the nanite block. But the general problem here is that the server build the projection and not a player, so i'm not sure that this meets your requirement.
